# Generated by Django 5.1.15 on 2026-09-15 06:16

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('requirements', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), size=None)),
                ('location', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('Engineering', 'Engineering'), ('Design', 'Design'), ('Product', 'Product'), ('Data', 'Data'), ('Marketing', 'Marketing'), ('Sales', 'Sales'), ('Operations', 'Operations'), ('Customer Support', 'Customer Support'), ('Finance', 'Finance')], max_length=40)),
                ('employment_type', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Internship', 'Internship')], max_length=20)),
                ('salary_min', models.PositiveIntegerField()),
                ('salary_max', models.PositiveIntegerField()),
                ('salary_currency', models.CharField(choices=[('USD', 'USD'), ('GBP', 'GBP'), ('EUR', 'EUR')], default='USD', max_length=3)),
                ('salary_period', models.CharField(choices=[('year', 'year'), ('month', 'month'), ('hour', 'hour')], default='year', max_length=10)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=10)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='accounts.employer')),
            ],
            options={
                'ordering': ['-posted_at', '-id'],
                'indexes': [models.Index(fields=['-posted_at'], name='job_posted_at_idx'), models.Index(fields=['category'], name='job_category_idx'), models.Index(fields=['-salary_max'], name='job_salary_max_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('salary_max__gte', models.F('salary_min'))), name='job_salary_max_gte_min')],
            },
        ),
    ]
